/*  PROPERTIES */
export const PROPERTIES_READ = 'PROPERTIES_READ';
export const PROPERTIES_READ_SUCCESS = 'PROPERTIES_READ_SUCCESS';
export const PROPERTIES_READ_ERR = 'PROPERTIES_READ_ERR';

export const SELECT_PROPERTIE = "SELECT_PROPERTIE";

/*  PAGINATOR */
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_PROPERTIES_PER_PAGE = 'SET_PROPERTIES_PER_PAGE';